- name: Install necessary packages
  tags: db, postgres
  apt:
    name: "{{ necessary_packages }}"
    state: present
    update_cache: yes

- name: Install PostgreSQL packages
  tags: db, postgres
  apt:
    name: "{{ postgres_packages }}"
    state: present
    update_cache: yes
  notify: Start PostgreSQL service

- name: Create the database
  tags: db, postgres
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    state: present

- name: Create users with access to the database
  tags: db, postgres
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ item }}"
    password: "{{ db_password }}"
    priv: all
    state: present
  with_items: "{{ db_users }}"

- name: Ensure database users does not have unnecessary permissions
  tags: db, postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ item }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  with_items: "{{ db_users }}"

- name: Copy dump file to server
  tags: db, postgres
  copy:
    src: dump.sql
    dest: /tmp/dump.sql
    owner: postgres
    group: postgres
    mode: 0644

- name: Fill database with dump
  tags: db, postgres
  become: true
  become_user: postgres
  shell: psql app < /tmp/dump.sql
