---
- name: Basic set up
  hosts: all
  roles:
    - base

- name: Set up web server
  hosts: web
  roles:
    - web

- name: Set up db server
  hosts: db
  roles:
    - db

- name: Set up api server
  hosts: api
  roles:
    - api
