---
- name: Basic set up
  hosts: all
  tasks:
    - name: create zrp user
      user:
        name: zrp
        groups: root

    - name: add sudoers file for zrp
      copy:
        src: zrp_sudoers
        dest: /etc/sudoers.d/zrp
        owner: root
        group: root
        mode: 0440

    - name: Install git 
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install vim-nox 
      apt:
        name: vim-nox
        state: present
        update_cache: yes

    - name: Install tmux 
      apt:
        name: tmux
        update_cache: yes
        state: present

- name: Set up web server
  hosts: web 
  vars:
    page_title: Linux >>> Windows
    gif_url: 'https://media.giphy.com/media/Ju7l5y9osyymQ/giphy.gif'
    apache_package: apache2
    index_file_template: index.html.j2
    index_file_path: /var/www/html/index.html
  tasks:
    - name: Install apache 
      apt:
        name: "{{ apache_package }}"
        state: present
        update_cache: yes

    - name: Copy index html file for site
      template:
        src: "{{ index_file_template }}"
        dest: "{{ index_file_path }}"
        owner: root
        group: root
        mode: 0644

- name: Set up db server
  hosts: db
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - openssl
        - libssl-dev
        - libssl-doc

    - name: Install PostgreSQL packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
      notify: Start PostgreSQL service

    - name: Create the database
      become: true
      become_user: postgres
      postgresql_db:
        name: app
        state: present

    - name: Create users with access to the database
      become: true
      become_user: postgres
      postgresql_user:
        db: app
        name: "{{ item }}"
        password: zrp@1234
        priv: ALL
        state: present
      with_items:
        - app
        - zrp

    - name: Ensure app user does not have unnecessary permissions
      become: true
      become_user: postgres
      postgresql_user:
        name: app
        role_attr_flags: NOSUPERUSER,NOCREATEDB
        state: present

    - name: Ensure zrp user does not have unnecessary permissions
      become: true
      become_user: postgres
      postgresql_user:
        name: zrp
        role_attr_flags: NOSUPERUSER,NOCREATEDB
        state: present

    - name: Copy dump file to server
      copy:
        src: dump.sql
        dest: /tmp/dump.sql
        owner: postgres
        group: postgres
        mode: 0644

    - name: Fill database with dump
      become: true
      become_user: postgres
      shell: psql app < /tmp/dump.sql
  handlers:
    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

- name: Set up api server
  hosts: api
  tasks:
    - name: Install the gpg key for nodejs
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs package
      apt:
        name: nodejs
        state: present

    - name: Install express generator
      become_user: zrp
      command: npm install express-generator -g

    - name: Generate app
      become_user: zrp
      command: express --view=pug myapp
      args:
        chdir: /opt/
        creates: /opt/myapp

    - name: Install dependencies
      become_user: zrp
      command: npm install
      args:
        chdir: /opt/myapp

    - name: Start server
      become_user: zrp
      shell: echo "npm start" | at now
      args:
        chdir: /opt/myapp
